# Generated by Django 6.0.3 on 2026-03-23 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_intervention'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='warranty_end_date',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='date',
        ),
    ]
